
import java.awt.Color;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WeSon8840
 */
public class game extends javax.swing.JFrame {
    String selected1="",selected2="";
    boolean t=false;
    ArrayList<String> a=new ArrayList<>(),b=new ArrayList<>();
    
    /**
     * Creates new form game
     */
    public game() {
        a.add("calcium");
        a.add("fluorine");
        a.add("copper");
        a.add("chlorine");
        a.add("oxrgen");
        a.add("nitrogen");
        a.add("sodium");
        a.add("aluminium");
        a.add("potassium");
        a.add("iron");
        a.add("carbon");
        a.add("silver");
        a.add("hydrogen");
        a.add("phosphorus");
        a.add("magnesium");
        b.add("ca");
        b.add("f");
        b.add("cu");
        b.add("cl");
        b.add("o");
        b.add("n");
        b.add("na");
        b.add("al");
        b.add("k");
        b.add("fe");
        b.add("c");
        b.add("ag");
        b.add("h");
        b.add("p");
        b.add("mg");
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        H = new javax.swing.JLabel();
        Fe = new javax.swing.JLabel();
        Na = new javax.swing.JLabel();
        Ca = new javax.swing.JLabel();
        K = new javax.swing.JLabel();
        Mg = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        O = new javax.swing.JLabel();
        N = new javax.swing.JLabel();
        Cl = new javax.swing.JLabel();
        Hydrogen = new javax.swing.JLabel();
        Potassium = new javax.swing.JLabel();
        Sodium = new javax.swing.JLabel();
        Calcium = new javax.swing.JLabel();
        Iron = new javax.swing.JLabel();
        Magnesium = new javax.swing.JLabel();
        Carbon = new javax.swing.JLabel();
        Aluminium = new javax.swing.JLabel();
        Nitrogen = new javax.swing.JLabel();
        Oxygen = new javax.swing.JLabel();
        F = new javax.swing.JLabel();
        Al = new javax.swing.JLabel();
        P = new javax.swing.JLabel();
        Fluorine = new javax.swing.JLabel();
        Chlorine = new javax.swing.JLabel();
        Phosphorus = new javax.swing.JLabel();
        Copper = new javax.swing.JLabel();
        Sliver = new javax.swing.JLabel();
        Ag = new javax.swing.JLabel();
        Cu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 500));
        getContentPane().setLayout(null);

        H.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        H.setText("H");
        H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HMouseClicked(evt);
            }
        });
        getContentPane().add(H);
        H.setBounds(257, 185, 13, 22);

        Fe.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Fe.setText("Fe");
        Fe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FeMouseClicked(evt);
            }
        });
        getContentPane().add(Fe);
        Fe.setBounds(456, 126, 21, 22);

        Na.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Na.setText("Na");
        Na.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NaMouseClicked(evt);
            }
        });
        getContentPane().add(Na);
        Na.setBounds(119, 95, 21, 22);

        Ca.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Ca.setText("Ca");
        Ca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CaMouseClicked(evt);
            }
        });
        getContentPane().add(Ca);
        Ca.setBounds(339, 242, 22, 22);

        K.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        K.setText("K");
        K.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KMouseClicked(evt);
            }
        });
        getContentPane().add(K);
        K.setBounds(491, 376, 11, 22);

        Mg.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Mg.setText("Mg");
        Mg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MgMouseClicked(evt);
            }
        });
        getContentPane().add(Mg);
        Mg.setBounds(162, 244, 28, 22);

        C.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        C.setText("C");
        C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMouseClicked(evt);
            }
        });
        getContentPane().add(C);
        C.setBounds(447, 330, 13, 22);

        O.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        O.setText("O");
        O.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OMouseClicked(evt);
            }
        });
        getContentPane().add(O);
        O.setBounds(419, 167, 15, 22);

        N.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        N.setText("N");
        N.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NMouseClicked(evt);
            }
        });
        getContentPane().add(N);
        N.setBounds(91, 330, 12, 22);

        Cl.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Cl.setText("Cl");
        Cl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClMouseClicked(evt);
            }
        });
        getContentPane().add(Cl);
        Cl.setBounds(138, 293, 18, 22);

        Hydrogen.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Hydrogen.setText("Hydrogen");
        Hydrogen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HydrogenMouseClicked(evt);
            }
        });
        getContentPane().add(Hydrogen);
        Hydrogen.setBounds(290, 318, 87, 22);

        Potassium.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Potassium.setText("Potassium");
        Potassium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PotassiumMouseClicked(evt);
            }
        });
        getContentPane().add(Potassium);
        Potassium.setBounds(220, 225, 87, 22);

        Sodium.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Sodium.setText("Sodium");
        Sodium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SodiumMouseClicked(evt);
            }
        });
        getContentPane().add(Sodium);
        Sodium.setBounds(175, 185, 64, 22);

        Calcium.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Calcium.setText("Calcium");
        Calcium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalciumMouseClicked(evt);
            }
        });
        getContentPane().add(Calcium);
        Calcium.setBounds(175, 63, 65, 22);

        Iron.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Iron.setText("Iron");
        Iron.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IronMouseClicked(evt);
            }
        });
        getContentPane().add(Iron);
        Iron.setBounds(204, 270, 35, 22);

        Magnesium.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Magnesium.setText("Magnesium");
        Magnesium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MagnesiumMouseClicked(evt);
            }
        });
        getContentPane().add(Magnesium);
        Magnesium.setBounds(290, 376, 96, 22);

        Carbon.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Carbon.setText("Carbon");
        Carbon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarbonMouseClicked(evt);
            }
        });
        getContentPane().add(Carbon);
        Carbon.setBounds(290, 270, 62, 22);

        Aluminium.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Aluminium.setText("Aluminium");
        Aluminium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AluminiumMouseClicked(evt);
            }
        });
        getContentPane().add(Aluminium);
        Aluminium.setBounds(288, 185, 83, 22);

        Nitrogen.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Nitrogen.setText("Nitrogen");
        Nitrogen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NitrogenMouseClicked(evt);
            }
        });
        getContentPane().add(Nitrogen);
        Nitrogen.setBounds(288, 146, 77, 22);

        Oxygen.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Oxygen.setText("Oxygen");
        Oxygen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OxygenMouseClicked(evt);
            }
        });
        getContentPane().add(Oxygen);
        Oxygen.setBounds(175, 146, 66, 22);

        F.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        F.setText("F");
        F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FMouseClicked(evt);
            }
        });
        getContentPane().add(F);
        F.setBounds(419, 90, 10, 22);

        Al.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Al.setText("Al");
        Al.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlMouseClicked(evt);
            }
        });
        getContentPane().add(Al);
        Al.setBounds(394, 280, 17, 22);

        P.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        P.setText("P");
        P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMouseClicked(evt);
            }
        });
        getContentPane().add(P);
        P.setBounds(50, 376, 11, 22);

        Fluorine.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Fluorine.setText("Fluorine");
        Fluorine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FluorineMouseClicked(evt);
            }
        });
        getContentPane().add(Fluorine);
        Fluorine.setBounds(288, 63, 69, 22);

        Chlorine.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Chlorine.setText("Chlorine");
        Chlorine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChlorineMouseClicked(evt);
            }
        });
        getContentPane().add(Chlorine);
        Chlorine.setBounds(288, 106, 73, 22);

        Phosphorus.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Phosphorus.setText("Phosphorus");
        Phosphorus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhosphorusMouseClicked(evt);
            }
        });
        getContentPane().add(Phosphorus);
        Phosphorus.setBounds(138, 376, 101, 22);

        Copper.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Copper.setText("Copper");
        Copper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CopperMouseClicked(evt);
            }
        });
        getContentPane().add(Copper);
        Copper.setBounds(175, 106, 65, 22);

        Sliver.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Sliver.setText("Silver");
        Sliver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SliverMouseClicked(evt);
            }
        });
        getContentPane().add(Sliver);
        Sliver.setBounds(188, 318, 51, 22);

        Ag.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Ag.setText("Ag");
        Ag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgMouseClicked(evt);
            }
        });
        getContentPane().add(Ag);
        Ag.setBounds(79, 134, 24, 22);

        Cu.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Cu.setText("Cu");
        Cu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CuMouseClicked(evt);
            }
        });
        getContentPane().add(Cu);
        Cu.setBounds(119, 176, 22, 22);

        jLabel1.setFont(new java.awt.Font("Nueva Std", 0, 22)); // NOI18N
        jLabel1.setText("Find my Brother ! !");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 168, 23);

        BackButton.setFont(new java.awt.Font("Lint McCree Intl BB", 0, 11)); // NOI18N
        BackButton.setForeground(new java.awt.Color(0, 51, 204));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(464, 12, 67, 23);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void CalciumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalciumMouseClicked
        if(!t){
            t=true;
            selected1="calcium";
            Calcium.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="calcium"){
                selected1="";
                Calcium.setForeground(new Color(0,0,0));
            }else{
                selected2="calcium";
                if(check()){
                    Calcium.setText("");
                    Ca.setText("");
                }else{
                    Calcium.setForeground(new Color(0,0,0));
                    Ca.setForeground(new Color(0,0,0));
                }
            }
            t=false;
        }
    }//GEN-LAST:event_CalciumMouseClicked

    private void CaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CaMouseClicked
         if(!t){
            t=true;
            selected1="ca";
            Ca.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="ca"){
                selected1="";
                Ca.setForeground(new Color(0,0,0));
            }else{
                selected2="ca";
                if(check()){
                    Calcium.setText("");
                    Ca.setText("");
                }
            }
            t=false;
        }
        
    }//GEN-LAST:event_CaMouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new Inc().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void FluorineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FluorineMouseClicked
        if(!t){
            t=true;
            selected1="fluorine";
            Fluorine.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="fluorine"){
                selected1="";
                Fluorine.setForeground(new Color(0,0,0));
            }else{
                selected2="fluorine";
                if(check()){
                    Fluorine.setText("");
                    F.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_FluorineMouseClicked

    private void FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FMouseClicked
        if(!t){
            t=true;
            selected1="f";
            F.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="f"){
                selected1="";
                F.setForeground(new Color(0,0,0));
            }else{
                selected2="f";
                if(check()){
                    Fluorine.setText("");
                    F.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_FMouseClicked

    private void CopperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CopperMouseClicked
        if(!t){
            t=true;
            selected1="copper";
            Copper.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="copper"){
                selected1="";
                Copper.setForeground(new Color(0,0,0));
            }else{
                selected2="copper";
                if(check()){
                    Copper.setText("");
                    Cu.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_CopperMouseClicked

    private void CuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CuMouseClicked
        if(!t){
            t=true;
            selected1="cu";
            Cu.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="cu"){
                selected1="";
                Cu.setForeground(new Color(0,0,0));
            }else{
                selected2="cu";
                if(check()){
                    Copper.setText("");
                    Cu.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_CuMouseClicked

    private void ChlorineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChlorineMouseClicked
        if(!t){
            t=true;
            selected1="chlorine";
            Chlorine.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="chlorine"){
                selected1="";
                Chlorine.setForeground(new Color(0,0,0));
            }else{
                selected2="chlorine";
                if(check()){
                    Chlorine.setText("");
                    Cl.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_ChlorineMouseClicked

    private void ClMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClMouseClicked
        if(!t){
            t=true;
            selected1="cl";
            Cl.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="cl"){
                selected1="";
                Cl.setForeground(new Color(0,0,0));
            }else{
                selected2="cl";
                if(check()){
                    Chlorine.setText("");
                    Cl.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_ClMouseClicked

    private void OxygenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OxygenMouseClicked
        if(!t){
            t=true;
            selected1="oxygen";
            Oxygen.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="oxygen"){
                selected1="";
                Oxygen.setForeground(new Color(0,0,0));
            }else{
                selected2="oxygen";
                if(check()){
                    Oxygen.setText("");
                    O.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_OxygenMouseClicked

    private void OMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OMouseClicked
        if(!t){
            t=true;
            selected1="o";
            O.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="o"){
                selected1="";
                O.setForeground(new Color(0,0,0));
            }else{
                selected2="o";
                if(check()){
                    Oxygen.setText("");
                    O.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_OMouseClicked

    private void NitrogenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NitrogenMouseClicked
        if(!t){
            t=true;
            selected1="nitrogen";
            Nitrogen.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="nitrogen"){
                selected1="";
                Nitrogen.setForeground(new Color(0,0,0));
            }else{
                selected2="nitrogen";
                if(check()){
                    Nitrogen.setText("");
                    N.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_NitrogenMouseClicked

    private void NMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NMouseClicked
        if(!t){
            t=true;
            selected1="n";
            N.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="n"){
                selected1="";
                N.setForeground(new Color(0,0,0));
            }else{
                selected2="n";
                if(check()){
                    Nitrogen.setText("");
                    N.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_NMouseClicked

    private void SodiumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SodiumMouseClicked
        if(!t){
            t=true;
            selected1="sodium";
            Sodium.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="sodium"){
                selected1="";
                Sodium.setForeground(new Color(0,0,0));
            }else{
                selected2="sodium";
                if(check()){
                    Sodium.setText("");
                    Na.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_SodiumMouseClicked

    private void NaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NaMouseClicked
        if(!t){
            t=true;
            selected1="na";
            Na.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="na"){
                selected1="";
                Na.setForeground(new Color(0,0,0));
            }else{
                selected2="na";
                if(check()){
                    Sodium.setText("");
                    Na.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_NaMouseClicked

    private void AluminiumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AluminiumMouseClicked
        if(!t){
            t=true;
            selected1="aluminium";
            Aluminium.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="aluminium"){
                selected1="";
                Aluminium.setForeground(new Color(0,0,0));
            }else{
                selected2="aluminium";
                if(check()){
                    Aluminium.setText("");
                    Al.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_AluminiumMouseClicked

    private void AlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlMouseClicked
        if(!t){
            t=true;
            selected1="al";
            Al.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="al"){
                selected1="";
                Al.setForeground(new Color(0,0,0));
            }else{
                selected2="al";
                if(check()){
                    Aluminium.setText("");
                    Al.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_AlMouseClicked

    private void PotassiumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PotassiumMouseClicked
        if(!t){
            t=true;
            selected1="potassium";
            Potassium.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="potassium"){
                selected1="";
                Potassium.setForeground(new Color(0,0,0));
            }else{
                selected2="potassium";
                if(check()){
                    Potassium.setText("");
                    K.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_PotassiumMouseClicked

    private void KMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KMouseClicked
        if(!t){
            t=true;
            selected1="k";
            K.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="k"){
                selected1="";
                K.setForeground(new Color(0,0,0));
            }else{
                selected2="k";
                if(check()){
                    Potassium.setText("");
                    K.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_KMouseClicked

    private void IronMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IronMouseClicked
        if(!t){
            t=true;
            selected1="iron";
            Iron.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="iron"){
                selected1="";
                Iron.setForeground(new Color(0,0,0));
            }else{
                selected2="iron";
                if(check()){
                    Iron.setText("");
                    Fe.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_IronMouseClicked

    private void FeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeMouseClicked
        if(!t){
            t=true;
            selected1="fe";
            Fe.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="fe"){
                selected1="";
                Fe.setForeground(new Color(0,0,0));
            }else{
                selected2="fe";
                if(check()){
                    Iron.setText("");
                    Fe.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_FeMouseClicked

    private void CarbonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarbonMouseClicked
        if(!t){
            t=true;
            selected1="carbon";
            Carbon.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="carbon"){
                selected1="";
                Carbon.setForeground(new Color(0,0,0));
            }else{
                selected2="carbon";
                if(check()){
                    Carbon.setText("");
                    C.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_CarbonMouseClicked

    private void CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMouseClicked
        if(!t){
            t=true;
            selected1="c";
            C.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="c"){
                selected1="";
                C.setForeground(new Color(0,0,0));
            }else{
                selected2="c";
                if(check()){
                    Carbon.setText("");
                    C.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_CMouseClicked

    private void SliverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SliverMouseClicked
        if(!t){
            t=true;
            selected1="sliver";
            Sliver.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="sliver"){
                selected1="";
                Sliver.setForeground(new Color(0,0,0));
            }else{
                selected2="sliver";
                if(check()){
                    Sliver.setText("");
                    Ag.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_SliverMouseClicked

    private void AgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgMouseClicked
        if(!t){
            t=true;
            selected1="ag";
            Ag.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="ag"){
                selected1="";
                Ag.setForeground(new Color(0,0,0));
            }else{
                selected2="ag";
                if(check()){
                    Sliver.setText("");
                    Ag.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_AgMouseClicked

    private void HydrogenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HydrogenMouseClicked
        if(!t){
            t=true;
            selected1="hydrogen";
            Hydrogen.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="hrdrogen"){
                selected1="";
                Hydrogen.setForeground(new Color(0,0,0));
            }else{
                selected2="hrdrogen";
                if(check()){
                    Hydrogen.setText("");
                    H.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_HydrogenMouseClicked

    private void HMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HMouseClicked
        if(!t){
            t=true;
            selected1="h";
            H.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="h"){
                selected1="";
                H.setForeground(new Color(0,0,0));
            }else{
                selected2="h";
                if(check()){
                    Hydrogen.setText("");
                    H.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_HMouseClicked

    private void PhosphorusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhosphorusMouseClicked
        if(!t){
            t=true;
            selected1="phosphorus";
            Phosphorus.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="phosphorus"){
                selected1="";
                Phosphorus.setForeground(new Color(0,0,0));
            }else{
                selected2="phosphorus";
                if(check()){
                    Phosphorus.setText("");
                    P.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_PhosphorusMouseClicked

    private void PMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMouseClicked
        if(!t){
            t=true;
            selected1="p";
            P.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="p"){
                selected1="";
                P.setForeground(new Color(0,0,0));
            }else{
                selected2="p";
                if(check()){
                    Phosphorus.setText("");
                    P.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_PMouseClicked

    private void MagnesiumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MagnesiumMouseClicked
        if(!t){
            t=true;
            selected1="magnesium";
            Magnesium.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="magnesium"){
                selected1="";
                Magnesium.setForeground(new Color(0,0,0));
            }else{
                selected2="magnesium";
                if(check()){
                    Magnesium.setText("");
                    Mg.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_MagnesiumMouseClicked

    private void MgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MgMouseClicked
        if(!t){
            t=true;
            selected1="mg";
            Mg.setForeground(new Color(255,0,0));
        }else{
            if(selected1=="mg"){
                selected1="";
                Mg.setForeground(new Color(0,0,0));
            }else{
                selected2="mg";
                if(check()){
                    Magnesium.setText("");
                    Mg.setText("");
                }
            }
            t=false;
        }
    }//GEN-LAST:event_MgMouseClicked
    public boolean check(){
        int m,n;
        if(a.indexOf(selected1)>=0){
            m=a.indexOf(selected1);
            n=b.indexOf(selected2);
        }else{
            m=a.indexOf(selected2);
            n=b.indexOf(selected1);
        }
        return m==n;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ag;
    private javax.swing.JLabel Al;
    private javax.swing.JLabel Aluminium;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel C;
    private javax.swing.JLabel Ca;
    private javax.swing.JLabel Calcium;
    private javax.swing.JLabel Carbon;
    private javax.swing.JLabel Chlorine;
    private javax.swing.JLabel Cl;
    private javax.swing.JLabel Copper;
    private javax.swing.JLabel Cu;
    private javax.swing.JLabel F;
    private javax.swing.JLabel Fe;
    private javax.swing.JLabel Fluorine;
    private javax.swing.JLabel H;
    private javax.swing.JLabel Hydrogen;
    private javax.swing.JLabel Iron;
    private javax.swing.JLabel K;
    private javax.swing.JLabel Magnesium;
    private javax.swing.JLabel Mg;
    private javax.swing.JLabel N;
    private javax.swing.JLabel Na;
    private javax.swing.JLabel Nitrogen;
    private javax.swing.JLabel O;
    private javax.swing.JLabel Oxygen;
    private javax.swing.JLabel P;
    private javax.swing.JLabel Phosphorus;
    private javax.swing.JLabel Potassium;
    private javax.swing.JLabel Sliver;
    private javax.swing.JLabel Sodium;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
